version : '3.4'

networks:
  loki:
    driver: bridge

services:
  api:
    image: ferrarijose/pedelogo-catalogo:v1
    ports:
        - 8080:80
    environment:
      Mongo__Host: mongodb
      Mongo__User: mongouser
      Mongo__Password: mongopwd
      Mongo__Port: 27017
      Mongo__Database: admin
    depends_on:
      - mongodb
    networks:
      - loki
    volumes:
      - './logs/api:/log'
  mongodb:
    image: mongo:5.0.12
    networks:
      - loki
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - loki     
  prontail:
    image: grafana/promtail:2.0.0
    command: -config.file=/etc/prontail/config.yaml
    volumes: 
      - "./prontail/config.yaml:/etc/prontail/config.yaml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - loki  
    ports:
      - 9080:9080
