apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email:  ferrariluizjose@gmail.com
    privatekeySecretRef:
      name: lestsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik