apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-state
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-state
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: volume-page
          image: busybox
          command: ['sh', '-c', 'echo $(hostmane) > /usr/share/nginx/html/idenx.html']
          volumeMounts: 
          - mountPath: /usr/share/nginx/html
            name: www
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        - volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
