global:
route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 5m

  routes:
  - receiver: MongoDBAlert
    match:
      team: mongodb

  - receiver: WebAPIAlert
    match:
      team: webapi

receivers:
- name: Default
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'
- name: MongoDBAlert
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookmongodb'
- name: WebAPIAlert
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookwebapi'
